export const LINK_INPUT = 'LINK_INPUT';
export const LINK_PARSE_SUCCSES = 'LINK_INPUT:SUCCSES'
export const LINK_PARSE_FAILED = 'LINK_INPUT:FAILED'
export const FETCH_DATA = 'FETCH_DATA:GET'
export const FETCH_DATA_SUCCSES = 'FETCH_DATA:SUCCSES'
export const FETCH_DATA_FAILED = 'FETCH_DATA:FAILED'